###

https://server.dev:8443/users/cards/getAll
Authorization:6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==

###
https://server.dev:8443/users/cards/getAll
Authorization: 1NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==

###

https://server.dev:8443/users/cards/getAll/2
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==

###


https://server.dev:8443/users/cards/getAll
Cookie:token=6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==

###
https://server.dev:8443/users/cards/1
Authorization:6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==

###

https://server.dev:8443/users/cards/getAll
Authorization:Basic 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==

###

https://server.dev:8443/users/cards/order
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==

###

DELETE https://server.dev:8443/users/cards/blockById/1
Authorization:6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==
###

DELETE https://server.dev:8443/users/cards/blockById/2
Authorization:6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==
###
DELETE https://server.dev:8443/users/cards/blockById/1
###

https://server.dev:8443/users/cards/order

###

POST https://server.dev:8443/users/register
Content-Type: application/json

{
  "username": {{$uuid}},
  "password": "password"
}

###

https://server.dev:8443/users/cards/getAll
Authorization: {{registration_token}}

###

POST https://server.dev:8443/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "newpass"
}

###

https://server.dev:8443/users/cards/getAll
Authorization: {{login_token}}

###

POST https://server.dev:8443/users/cards/1/transaction
Authorization: 6NSb+2kcdKF44ut4iBu+dm6YLu6pakWapvxHtxqaPgMr5iRhox/HlhBerAZMILPjwnRtXms+zDfVTLCsao9nuw==
Content-Type: application/json

{
  "addresseeCardId": 3,
  "sum": 10000
}

###
GET https://server.dev:8443/users/passRecovery/admin

###

POST https://server.dev:8443/users/passRecovery
Content-Type: application/json

{
  "username": "admin",
  "password": "newpass",
  "code": 598403
}

###
https://server.dev:8443/users/cards/getAll
Authorization:Basic YWRtaW46bmV3cGFzcw==